const crash = (reason) => ***REMOVED***
  process.on(reason, (err) => ***REMOVED***
    console.error(reason, err.stack)
    process.exit(-1)
***REMOVED***)
}

crash('unhandledRejection')
crash('uncaughtError')
crash('warning')
